Create PCA colormap for images with channels > 3
nerfstudio-project/nerfstudio pull request #1929
Opened 2023-05-15 22:54 UTC by chungmin99

Current colormap supports 3-channel (RGB) and 1-channel (depth, accumulation).

It would be useful to support colormaps for n-channel images for research visualization. (e.g., images with DINO features, ...) 

@kerrj for reference

2023-05-15 23:23 UTC, SauravMaheshkar requested changes
Please run `black` on the changed files for the CI to pass.

2023-05-15 23:31 UTC, tancik reviewed
This is great! Can you add a screenshot of it working to the PR description?

2023-05-15 23:31 UTC, tancik commented on nerfstudio/utils/colormaps.py
> +def apply_pca_colormap(image):
Add types

2023-05-15 23:45 UTC, tancik commented on nerfstudio/utils/colormaps.py
> +    if image.shape[-1] > 3:
Can you update the docstring to inform users that PCA is used when >3 channels (line 51)

2023-05-16 17:40 UTC, kerrj approved these changes
lgtm

2023-05-16 17:46 UTC, merged