Fixes nerfstudio-project/nerfstudio#3004
nerfstudio-project/nerfstudio pull request #3005
Opened 2024-03-15 15:40 UTC by mathijshenquet

See nerfstudio-project/nerfstudio#3004

I could not figure a clean way to do it with the open3d library.

The ply file produced by this patch has been verified to be loadable by aras-p/UnityGaussianSplatting and antimatter15/splat

2024-03-15 18:21 UTC, jb-ye commented
`plyfile` package is GPLv3, so we couldn't really use this library as it is copyleft by nature.

2024-03-18 06:58 UTC, akristoffersen requested changes
Thanks for contributing! Just some small comments but otherwise looks good to go 👍

2024-03-18 06:58 UTC, akristoffersen commented on nerfstudio/scripts/exporter.py
> +            # WRite properties, in order thanks to OrderedDict
```suggestion
            # Write properties, in order thanks to OrderedDict
```

2024-03-18 06:58 UTC, akristoffersen commented on nerfstudio/scripts/exporter.py
> +            #select = np.logical_and(select, np.isfinite(t).all(axis=1))
remove comment

2024-03-18 06:58 UTC, akristoffersen commented on nerfstudio/scripts/exporter.py
> +    def write_ply(self, filename, count, map_to_tensors: OrderedDict):
Could you add a short doc-string for this helper method? I could also see this as a class / static method since it doesn't look like relies on self.

2024-03-18 08:48 UTC, mathijshenquet commented
@akristoffersen I addressed your comments and added some additional checks and documentation

2024-03-18 17:05 UTC, kerrj approved these changes
lgtm, thanks!

2024-03-20 19:48 UTC, akristoffersen approved these changes

2024-03-20 19:48 UTC, merged