Write camera path to output dir if saving to the data dir fails
nerfstudio-project/nerfstudio pull request #3476
Opened 2024-10-14 13:04 UTC by krahets

If we load data from a folder without write permissions, the `Generate Command` button in the render panel will not respond.

A simple solution is to write it to the output directory if writing to the data folder fails.

<img width="438" alt="image" src="https://github.com/user-attachments/assets/e235312f-08da-470e-a5b3-50b7f85e8bb6">

2024-10-14 18:15 UTC, kerrj requested changes
This looks good! can you also add some sort of log statement informing users that the data dir is unwritable and that it instead wrote the path to this location?

2024-10-16 12:17 UTC, krahets commented
Sure. Does this meet your expectations?

<img width="764" alt="image" src="https://github.com/user-attachments/assets/cf01b604-4391-45bd-97e8-74af5027bfa9">

2024-11-06 10:16 UTC, krahets commented
Hi @kerrj, is there any comment to be addressed?

2024-11-21 19:49 UTC, jb-ye commented
@krahets can you also fix the linter error in core tests?
```
Run ruff check docs/ nerfstudio/ tests/ --output-format=github
Error: nerfstudio/viewer/render_panel.py:15:1: I001 Import block is un-sorted or un-formatted
Error: nerfstudio/viewer/render_panel.py:[11](https://github.com/nerfstudio-project/nerfstudio/actions/runs/11401455191/job/31724388520?pr=3476#step:8:12)36:29: F841 Local variable `e` is assigned to but never used
Error: Process completed with exit code 1.
```

2024-12-09 19:15 UTC, krahets commented
@jb-ye Fxied

2025-01-03 19:37 UTC, kerrj approved these changes

2025-01-03 19:38 UTC, kerrj commented
Sorry for the delay thanks for the PR!

2025-01-08 09:10 UTC, merged